apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: granite-rhaiis
  namespace: rhaii-namespace
spec:
  to:
    kind: Service
    name: granite-rhaiis
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
